### ISSUE TITLE
oneliner

### ISSUE THREAD

**Issue by GameTec-live** [LyonSyonII/steam-deck-tools#1]
id be willing to create a subdomain for a easy oneliner, eg: curl https://decktools.gametec.org/ | sh

any interest? if not, just close it

**Comment by LyonSyonII** [comment]
It would be amazing, thank you for offering it!

We're currently discussing about changing the name of the tool, as Steam Deck Tools is already taken by another project, so it would be better to wait until the new name is chosen.

**Comment by LyonSyonII** [comment]
The name has been changed, it's now Lyon's Deck Toolbox.
I would appreciate if you could create the subdomain as https://decktoolbox.gametec.org/

**Comment by GameTec-live** [comment]
sure, ill go and make a readme change as soon as its ready...

**Comment by GameTec-live** [comment]
@LyonSyonII i added an entry that now calls a oneliner.sh from the root of the repo with the following command:
`dig +short -t txt dtb.gametec.org | tr -d '"' | sh`
